FROM node:lts AS builder
WORKDIR /app
COPY package*.json .
RUN npm i

COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
