services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=rsl_db"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - super-internet
volumes:
  db-data:
networks:
  super-internet:
